#! /bin/sh

# autostart
killall -q polybar

sxhkd & disown
bspwm-focus & disown
polybar custom & disown

#wal -i ~/Pictures/wallpapers/"wings of a warrior.jpg"
wal -i ~/Pictures/wallpapers/cloudbank.jpg


bspc monitor -d I II III IV V VI VII VIII IX

bspc config top_padding		30
bspc config border_width         3
bspc config window_gap           3
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

